name: CI with SonarQube

on:
  push:
    branches: [ main, ci, master, latest, 3.3-stable ]
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

permissions:
  contents: read
  statuses: write

jobs:
  # -------------------------------
  # Linux build
  # -------------------------------
  build-linux-clang:
    name: Linux (Clang)
    runs-on: ubuntu-latest
    timeout-minutes: 4
    env:
      CC: clang
      CFLAGS: -Werror
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libxrandr-dev libxinerama-dev libxcursor-dev \
            libxi-dev libxext-dev libwayland-dev libxkbcommon-dev

      - name: Build
        run: |
          cmake -B build
          cmake --build build --parallel

  # -------------------------------
  # macOS build
  # -------------------------------
  build-macos-clang:
    name: macOS (Clang)
    runs-on: macos-latest
    timeout-minutes: 4
    env:
      CFLAGS: -Werror
      MACOSX_DEPLOYMENT_TARGET: 10.11
      CMAKE_OSX_ARCHITECTURES: x86_64;arm64
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -B build
          cmake --build build --parallel

  # -------------------------------
  # Windows build
  # -------------------------------
  build-windows-vs2022:
    name: Windows (VS2022)
    runs-on: windows-latest
    timeout-minutes: 4
    env:
      CFLAGS: /WX
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -B build -G "Visual Studio 17 2022"
          cmake --build build --parallel

  # -------------------------------
  # SonarQube Scan (afte
